//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstMVCApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Album
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Album()
        {
            this.Artists = new HashSet<Artist>();
        }
    
        public int AlbumID { get; set; }
        [Display(Name = "Album")]
        public string Photo { get; set; }
        [Display(Name="Title")]
        public string AlbumName { get; set; }
        [Display(Name ="# of Tracks")]
        public string TrackAmount { get; set; }
        [Display(Name = "Grammy")]
        public bool WonGrammy { get; set; }
        [Display(Name ="Release Date")]
        public string YearReleased { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Artist> Artists { get; set; }
    }
}
